// Code generated by protoc-gen-ts_proto. DO NOT EDIT.
// versions:
//   protoc-gen-ts_proto  v2.11.10
//   protoc               v3.19.1
// source: auth.proto

/* eslint-disable */
import { GrpcMethod, GrpcStreamMethod } from '@nestjs/microservices';
import { Observable } from 'rxjs';

export const protobufPackage = 'auth';

export interface RegisterRequest {
  name: string;
  email: string;
  password: string;
}

export interface VerifyRegistrationRequest {
  email: string;
  otp: string;
}

export interface ResetPasswordRequest {
  email: string;
  otp: string;
  newPassword: string;
}

export interface ForgotPassRequest {
  email: string;
}

export interface BasicResponse {
  success: boolean;
  message: string;
}

export interface ChangePassRequest {
  userId: string;
  oldPassword: string;
  newPassword: string;
}

export interface LoginRequest {
  email: string;
  password: string;
  deviceId?: string | undefined;
  deviceFingerprint?: string | undefined;
  ipAddress?: string | undefined;
  userAgent?: string | undefined;
  twoFactorCode?: string | undefined;
}

export interface LogoutRequest {
  userId: string;
  sessionId?: string | undefined;
}

export interface VerifyTokenRequest {
  token: string;
  deviceFingerprint?: string | undefined;
}

export interface VerifyTokenResponse {
  valid: boolean;
  userId: string;
  email: string;
  role: string;
  message: string;
  deviceId?: string | undefined;
  sessionId?: string | undefined;
}

export interface RefreshTokenRequest {
  refreshToken: string;
  deviceId?: string | undefined;
  deviceFingerprint?: string | undefined;
}

export interface AuthResponse {
  success: boolean;
  accessToken: string;
  refreshToken: string;
  message: string;
  user: UserData | undefined;
}

export interface GetUserByIdRequest {
  userId: string;
}

export interface GetUserByEmailRequest {
  email: string;
}

export interface UserResponse {
  success: boolean;
  message: string;
  user: UserData | undefined;
}

export interface AllUsersResponse {
  success: boolean;
  message: string;
  users: UserData[];
}

export interface GetAllUsersRequest {
  page: number;
  limit: number;
}

export interface UserData {
  id: string;
  name: string;
  email: string;
  role: string;
  createdAt: string;
}

export interface RevokeSessionRequest {
  userId: string;
  sessionId: string;
}

export interface RevokeAllSessionsRequest {
  userId: string;
}

export interface GetActiveSessionsRequest {
  userId: string;
}

export interface SessionData {
  sessionId: string;
  deviceId: string;
  ipAddress: string;
  browser: string;
  os: string;
  lastActivity: string;
}

export interface ActiveSessionsResponse {
  success: boolean;
  sessions: SessionData[];
}

export interface VerifyMfaRequest {
  userId: string;
  code: string;
}

export interface VerifyMfaResponse {
  success: boolean;
  mfaToken: string;
}

export const AUTH_PACKAGE_NAME = 'auth';

export interface AuthServiceClient {
  register(request: RegisterRequest): Observable<BasicResponse>;

  verifyRegistration(
    request: VerifyRegistrationRequest,
  ): Observable<BasicResponse>;

  forgotPasswordRequest(request: ForgotPassRequest): Observable<BasicResponse>;

  resetPassword(request: ResetPasswordRequest): Observable<BasicResponse>;

  login(request: LoginRequest): Observable<AuthResponse>;

  logout(request: LogoutRequest): Observable<BasicResponse>;

  verifyToken(request: VerifyTokenRequest): Observable<VerifyTokenResponse>;

  refreshToken(request: RefreshTokenRequest): Observable<AuthResponse>;

  changePassword(request: ChangePassRequest): Observable<BasicResponse>;

  getUserById(request: GetUserByIdRequest): Observable<UserResponse>;

  getUserByEmail(request: GetUserByEmailRequest): Observable<UserResponse>;

  getAllUsers(request: GetAllUsersRequest): Observable<AllUsersResponse>;

  revokeSession(request: RevokeSessionRequest): Observable<BasicResponse>;

  revokeAllSessions(
    request: RevokeAllSessionsRequest,
  ): Observable<BasicResponse>;

  getActiveSessions(
    request: GetActiveSessionsRequest,
  ): Observable<ActiveSessionsResponse>;

  verifyMfa(request: VerifyMfaRequest): Observable<VerifyMfaResponse>;
}

export interface AuthServiceController {
  register(
    request: RegisterRequest,
  ): Promise<BasicResponse> | Observable<BasicResponse> | BasicResponse;

  verifyRegistration(
    request: VerifyRegistrationRequest,
  ): Promise<BasicResponse> | Observable<BasicResponse> | BasicResponse;

  forgotPasswordRequest(
    request: ForgotPassRequest,
  ): Promise<BasicResponse> | Observable<BasicResponse> | BasicResponse;

  resetPassword(
    request: ResetPasswordRequest,
  ): Promise<BasicResponse> | Observable<BasicResponse> | BasicResponse;

  login(
    request: LoginRequest,
  ): Promise<AuthResponse> | Observable<AuthResponse> | AuthResponse;

  logout(
    request: LogoutRequest,
  ): Promise<BasicResponse> | Observable<BasicResponse> | BasicResponse;

  verifyToken(
    request: VerifyTokenRequest,
  ):
    | Promise<VerifyTokenResponse>
    | Observable<VerifyTokenResponse>
    | VerifyTokenResponse;

  refreshToken(
    request: RefreshTokenRequest,
  ): Promise<AuthResponse> | Observable<AuthResponse> | AuthResponse;

  changePassword(
    request: ChangePassRequest,
  ): Promise<BasicResponse> | Observable<BasicResponse> | BasicResponse;

  getUserById(
    request: GetUserByIdRequest,
  ): Promise<UserResponse> | Observable<UserResponse> | UserResponse;

  getUserByEmail(
    request: GetUserByEmailRequest,
  ): Promise<UserResponse> | Observable<UserResponse> | UserResponse;

  getAllUsers(
    request: GetAllUsersRequest,
  ):
    | Promise<AllUsersResponse>
    | Observable<AllUsersResponse>
    | AllUsersResponse;

  revokeSession(
    request: RevokeSessionRequest,
  ): Promise<BasicResponse> | Observable<BasicResponse> | BasicResponse;

  revokeAllSessions(
    request: RevokeAllSessionsRequest,
  ): Promise<BasicResponse> | Observable<BasicResponse> | BasicResponse;

  getActiveSessions(
    request: GetActiveSessionsRequest,
  ):
    | Promise<ActiveSessionsResponse>
    | Observable<ActiveSessionsResponse>
    | ActiveSessionsResponse;

  verifyMfa(
    request: VerifyMfaRequest,
  ):
    | Promise<VerifyMfaResponse>
    | Observable<VerifyMfaResponse>
    | VerifyMfaResponse;
}

export function AuthServiceControllerMethods() {
  return function (constructor: Function) {
    const grpcMethods: string[] = [
      'register',
      'verifyRegistration',
      'forgotPasswordRequest',
      'resetPassword',
      'login',
      'logout',
      'verifyToken',
      'refreshToken',
      'changePassword',
      'getUserById',
      'getUserByEmail',
      'getAllUsers',
      'revokeSession',
      'revokeAllSessions',
      'getActiveSessions',
      'verifyMfa',
    ];
    for (const method of grpcMethods) {
      const descriptor: any = Reflect.getOwnPropertyDescriptor(
        constructor.prototype,
        method,
      );
      GrpcMethod('AuthService', method)(
        constructor.prototype[method],
        method,
        descriptor,
      );
    }
    const grpcStreamMethods: string[] = [];
    for (const method of grpcStreamMethods) {
      const descriptor: any = Reflect.getOwnPropertyDescriptor(
        constructor.prototype,
        method,
      );
      GrpcStreamMethod('AuthService', method)(
        constructor.prototype[method],
        method,
        descriptor,
      );
    }
  };
}

export const AUTH_SERVICE_NAME = 'AuthService';
