// Code generated by protoc-gen-ts_proto. DO NOT EDIT.
// versions:
//   protoc-gen-ts_proto  v2.11.10
//   protoc               v3.19.1
// source: chat.proto

/* eslint-disable */
import { GrpcMethod, GrpcStreamMethod } from '@nestjs/microservices';
import { Observable } from 'rxjs';

export const protobufPackage = 'chat';

export interface ConversationMember {
  userId: string;
  role: string;
  muted: boolean;
  mutedUntil?: string | undefined;
  archived: boolean;
  pinned: boolean;
  unreadCount: number;
  leftAt?: string | undefined;
  joinedAt: string;
}

export interface Conversation {
  id: string;
  participants: string[];
  /** direct | group */
  type: string;
  name: string;
  avatar: string;
  lastMessage: string;
  lastMessageAt: number;
  lastSenderId: string;
  unreadCounts: { [key: string]: number };
  admins: string[];
  isDeleted: boolean;
  createdAt: number;
  updatedAt: number;
  members: ConversationMember[];
}

export interface Conversation_UnreadCountsEntry {
  key: string;
  value: number;
}

export interface ConversationResponse {
  success: boolean;
  message: string;
  conversation: Conversation | undefined;
}

export interface Media {
  id: string;
  url: string;
  mimeType: string;
  type: string;
}

export interface User {
  id: string;
  username: string;
  fullName: string;
  avatar: string;
  verified: boolean;
}

export interface Message {
  id: string;
  conversationId: string;
  text: string;
  /** text | image | video | audio | file | gif */
  type: string;
  readBy: string[];
  reactions: { [key: string]: StringList };
  isDeleted: boolean;
  replyTo: string;
  createdAt: number;
  updatedAt: number;
  sender: User | undefined;
  media: Media[];
  forwardedFromMessageId?: string | undefined;
  clientMessageId?: string | undefined;
  isEdited: boolean;
  editedAt?: number | undefined;
  isPinned: boolean;
}

export interface Message_ReactionsEntry {
  key: string;
  value: StringList | undefined;
}

export interface StringList {
  values: string[];
}

export interface MessageResponse {
  success: boolean;
  message: string;
  messageData: Message | undefined;
}

export interface GetOrCreateConversationRequest {
  userId1: string;
  userId2: string;
}

export interface CreateGroupRequest {
  name: string;
  creatorId: string;
  participantIds: string[];
  avatar: string;
}

export interface AddGroupMemberRequest {
  conversationId: string;
  adminId: string;
  userId: string;
  role?: string | undefined;
}

export interface RemoveGroupMemberRequest {
  conversationId: string;
  adminId: string;
  userId: string;
}

export interface LeaveGroupRequest {
  conversationId: string;
  userId: string;
}

export interface UpdateMemberRoleRequest {
  conversationId: string;
  adminId: string;
  userId: string;
  role: string;
}

export interface MuteConversationRequest {
  conversationId: string;
  userId: string;
  muted: boolean;
  mutedUntil?: string | undefined;
}

export interface ArchiveConversationRequest {
  conversationId: string;
  userId: string;
  archived: boolean;
}

export interface PinConversationRequest {
  conversationId: string;
  userId: string;
  pinned: boolean;
}

export interface SendMessageRequest {
  conversationId: string;
  senderId: string;
  senderName: string;
  senderAvatar: string;
  text: string;
  mediaIds: string[];
  type: string;
  replyTo: string;
  forwardedFromMessageId?: string | undefined;
  clientMessageId?: string | undefined;
}

export interface GetMessagesRequest {
  conversationId: string;
  userId: string;
  page: number;
  limit: number;
  beforeMessageId?: string | undefined;
  afterMessageId?: string | undefined;
}

export interface GetMessagesResponse {
  messages: Message[];
  total: number;
  page: number;
  hasMore: boolean;
}

export interface EditMessageRequest {
  messageId: string;
  senderId: string;
  text: string;
}

export interface DeleteMessageRequest {
  messageId: string;
  userId: string;
  forEveryone: boolean;
}

export interface ForwardMessageRequest {
  sourceMessageId: string;
  targetConversationId: string;
  senderId: string;
}

export interface MarkReceiptRequest {
  messageId: string;
  userId: string;
  status: string;
}

export interface MarkAsReadRequest {
  conversationId: string;
  userId: string;
  upToMessageId?: string | undefined;
}

export interface ReactToMessageRequest {
  messageId: string;
  userId: string;
  emoji: string;
}

export interface PinMessageRequest {
  conversationId: string;
  messageId: string;
  userId: string;
  pinned: boolean;
}

export interface GetConversationsRequest {
  userId: string;
  page: number;
  limit: number;
  archived?: boolean | undefined;
}

export interface ConversationItem {
  id: string;
  type: string;
  name: string;
  avatar: string;
  participants: string[];
  lastMessage: string;
  lastMessageAt: number;
  lastSenderId: string;
  unreadCount: number;
  isOnline: boolean;
  muted: boolean;
  archived: boolean;
  pinned: boolean;
}

export interface GetConversationsResponse {
  conversations: ConversationItem[];
  total: number;
  page: number;
}

export interface GetConversationRequest {
  conversationId: string;
  userId: string;
}

export interface OperationResponse {
  success: boolean;
  message: string;
}

export interface GetUnreadCountsRequest {
  userId: string;
}

export interface UnreadCountItem {
  conversationId: string;
  count: number;
}

export interface GetUnreadCountsResponse {
  success: boolean;
  items: UnreadCountItem[];
  totalUnread: number;
}

export interface GetGroupMembersForNotifRequest {
  conversationId: string;
}

export interface GroupNotificationMember {
  userId: string;
  muted: boolean;
}

export interface GetGroupMembersForNotifResponse {
  success: boolean;
  conversationId: string;
  groupName: string;
  avatar: string;
  members: GroupNotificationMember[];
}

export const CHAT_PACKAGE_NAME = 'chat';

export interface ChatServiceClient {
  /** Direct conversation */

  getOrCreateConversation(
    request: GetOrCreateConversationRequest,
  ): Observable<ConversationResponse>;

  /** Group */

  createGroup(request: CreateGroupRequest): Observable<ConversationResponse>;

  addGroupMember(request: AddGroupMemberRequest): Observable<OperationResponse>;

  removeGroupMember(
    request: RemoveGroupMemberRequest,
  ): Observable<OperationResponse>;

  leaveGroup(request: LeaveGroupRequest): Observable<OperationResponse>;

  updateMemberRole(
    request: UpdateMemberRoleRequest,
  ): Observable<OperationResponse>;

  /** Settings */

  muteConversation(
    request: MuteConversationRequest,
  ): Observable<OperationResponse>;

  archiveConversation(
    request: ArchiveConversationRequest,
  ): Observable<OperationResponse>;

  pinConversation(
    request: PinConversationRequest,
  ): Observable<OperationResponse>;

  /** Messages */

  sendMessage(request: SendMessageRequest): Observable<MessageResponse>;

  getMessages(request: GetMessagesRequest): Observable<GetMessagesResponse>;

  editMessage(request: EditMessageRequest): Observable<MessageResponse>;

  deleteMessage(request: DeleteMessageRequest): Observable<OperationResponse>;

  forwardMessage(request: ForwardMessageRequest): Observable<MessageResponse>;

  /** Read status & Receipts */

  markReceipt(request: MarkReceiptRequest): Observable<OperationResponse>;

  markAsRead(request: MarkAsReadRequest): Observable<OperationResponse>;

  /** Reactions & Pins */

  reactToMessage(request: ReactToMessageRequest): Observable<MessageResponse>;

  pinMessage(request: PinMessageRequest): Observable<OperationResponse>;

  /** Conversation list & Single fetch */

  getConversations(
    request: GetConversationsRequest,
  ): Observable<GetConversationsResponse>;

  getConversation(
    request: GetConversationRequest,
  ): Observable<ConversationResponse>;

  /** Unread & Notifications */

  getUnreadCounts(
    request: GetUnreadCountsRequest,
  ): Observable<GetUnreadCountsResponse>;

  getGroupMembersForNotif(
    request: GetGroupMembersForNotifRequest,
  ): Observable<GetGroupMembersForNotifResponse>;
}

export interface ChatServiceController {
  /** Direct conversation */

  getOrCreateConversation(
    request: GetOrCreateConversationRequest,
  ):
    | Promise<ConversationResponse>
    | Observable<ConversationResponse>
    | ConversationResponse;

  /** Group */

  createGroup(
    request: CreateGroupRequest,
  ):
    | Promise<ConversationResponse>
    | Observable<ConversationResponse>
    | ConversationResponse;

  addGroupMember(
    request: AddGroupMemberRequest,
  ):
    | Promise<OperationResponse>
    | Observable<OperationResponse>
    | OperationResponse;

  removeGroupMember(
    request: RemoveGroupMemberRequest,
  ):
    | Promise<OperationResponse>
    | Observable<OperationResponse>
    | OperationResponse;

  leaveGroup(
    request: LeaveGroupRequest,
  ):
    | Promise<OperationResponse>
    | Observable<OperationResponse>
    | OperationResponse;

  updateMemberRole(
    request: UpdateMemberRoleRequest,
  ):
    | Promise<OperationResponse>
    | Observable<OperationResponse>
    | OperationResponse;

  /** Settings */

  muteConversation(
    request: MuteConversationRequest,
  ):
    | Promise<OperationResponse>
    | Observable<OperationResponse>
    | OperationResponse;

  archiveConversation(
    request: ArchiveConversationRequest,
  ):
    | Promise<OperationResponse>
    | Observable<OperationResponse>
    | OperationResponse;

  pinConversation(
    request: PinConversationRequest,
  ):
    | Promise<OperationResponse>
    | Observable<OperationResponse>
    | OperationResponse;

  /** Messages */

  sendMessage(
    request: SendMessageRequest,
  ): Promise<MessageResponse> | Observable<MessageResponse> | MessageResponse;

  getMessages(
    request: GetMessagesRequest,
  ):
    | Promise<GetMessagesResponse>
    | Observable<GetMessagesResponse>
    | GetMessagesResponse;

  editMessage(
    request: EditMessageRequest,
  ): Promise<MessageResponse> | Observable<MessageResponse> | MessageResponse;

  deleteMessage(
    request: DeleteMessageRequest,
  ):
    | Promise<OperationResponse>
    | Observable<OperationResponse>
    | OperationResponse;

  forwardMessage(
    request: ForwardMessageRequest,
  ): Promise<MessageResponse> | Observable<MessageResponse> | MessageResponse;

  /** Read status & Receipts */

  markReceipt(
    request: MarkReceiptRequest,
  ):
    | Promise<OperationResponse>
    | Observable<OperationResponse>
    | OperationResponse;

  markAsRead(
    request: MarkAsReadRequest,
  ):
    | Promise<OperationResponse>
    | Observable<OperationResponse>
    | OperationResponse;

  /** Reactions & Pins */

  reactToMessage(
    request: ReactToMessageRequest,
  ): Promise<MessageResponse> | Observable<MessageResponse> | MessageResponse;

  pinMessage(
    request: PinMessageRequest,
  ):
    | Promise<OperationResponse>
    | Observable<OperationResponse>
    | OperationResponse;

  /** Conversation list & Single fetch */

  getConversations(
    request: GetConversationsRequest,
  ):
    | Promise<GetConversationsResponse>
    | Observable<GetConversationsResponse>
    | GetConversationsResponse;

  getConversation(
    request: GetConversationRequest,
  ):
    | Promise<ConversationResponse>
    | Observable<ConversationResponse>
    | ConversationResponse;

  /** Unread & Notifications */

  getUnreadCounts(
    request: GetUnreadCountsRequest,
  ):
    | Promise<GetUnreadCountsResponse>
    | Observable<GetUnreadCountsResponse>
    | GetUnreadCountsResponse;

  getGroupMembersForNotif(
    request: GetGroupMembersForNotifRequest,
  ):
    | Promise<GetGroupMembersForNotifResponse>
    | Observable<GetGroupMembersForNotifResponse>
    | GetGroupMembersForNotifResponse;
}

export function ChatServiceControllerMethods() {
  return function (constructor: Function) {
    const grpcMethods: string[] = [
      'getOrCreateConversation',
      'createGroup',
      'addGroupMember',
      'removeGroupMember',
      'leaveGroup',
      'updateMemberRole',
      'muteConversation',
      'archiveConversation',
      'pinConversation',
      'sendMessage',
      'getMessages',
      'editMessage',
      'deleteMessage',
      'forwardMessage',
      'markReceipt',
      'markAsRead',
      'reactToMessage',
      'pinMessage',
      'getConversations',
      'getConversation',
      'getUnreadCounts',
      'getGroupMembersForNotif',
    ];
    for (const method of grpcMethods) {
      const descriptor: any = Reflect.getOwnPropertyDescriptor(
        constructor.prototype,
        method,
      );
      GrpcMethod('ChatService', method)(
        constructor.prototype[method],
        method,
        descriptor,
      );
    }
    const grpcStreamMethods: string[] = [];
    for (const method of grpcStreamMethods) {
      const descriptor: any = Reflect.getOwnPropertyDescriptor(
        constructor.prototype,
        method,
      );
      GrpcStreamMethod('ChatService', method)(
        constructor.prototype[method],
        method,
        descriptor,
      );
    }
  };
}

export const CHAT_SERVICE_NAME = 'ChatService';
