// Code generated by protoc-gen-ts_proto. DO NOT EDIT.
// versions:
//   protoc-gen-ts_proto  v2.11.10
//   protoc               v3.19.1
// source: e2ee-chat.proto

/* eslint-disable */
import { GrpcMethod, GrpcStreamMethod } from '@nestjs/microservices';
import { Observable } from 'rxjs';

export const protobufPackage = 'e2ee_chat';

export interface GetGroupMembersForNotifRequest {
  conversationId: string;
}

export interface GroupNotificationMember {
  userId: string;
  muted: boolean;
}

export interface GetGroupMembersForNotifResponse {
  success: boolean;
  conversationId: string;
  groupName: string;
  avatar: string;
  members: GroupNotificationMember[];
}

export interface OperationResponse {
  success: boolean;
  message: string;
}

export interface CipherPayload {
  ciphertext: string;
  iv: string;
  authTag: string;
  ratchetHeader?: string | undefined;
  ephemeralKey?: string | undefined;
  oneTimePreKeyId?: number | undefined;
  signedPreKeyId?: number | undefined;
}

export interface MessageEnvelope {
  recipientUserId: string;
  recipientDeviceId: string;
  payload: CipherPayload | undefined;
}

export interface EncryptedAttachment {
  mediaId: string;
  encryptedKey: string;
  mimeType?: string | undefined;
  sizeBytes?: number | undefined;
  fileName?: string | undefined;
}

export interface ConversationMember {
  userId: string;
  role: string;
  muted: boolean;
  mutedUntil?: string | undefined;
  archived: boolean;
  pinned: boolean;
  unreadCount: number;
  leftAt?: string | undefined;
  joinedAt: string;
}

export interface Conversation {
  id: string;
  type: string;
  name?: string | undefined;
  avatar?: string | undefined;
  createdBy: string;
  isDeleted: boolean;
  lastMessageId?: string | undefined;
  lastMessageAt?: number | undefined;
  lastSenderId: string;
  members: ConversationMember[];
  createdAt: string;
  updatedAt: string;
}

export interface ConversationResponse {
  success: boolean;
  message: string;
  conversation: Conversation | undefined;
}

export interface ConversationItem {
  id: string;
  type: string;
  name?: string | undefined;
  avatar?: string | undefined;
  participantIds: string[];
  lastMessageId?: string | undefined;
  lastMessageAt?: number | undefined;
  lastSenderId: string;
  unreadCount: number;
  muted: boolean;
  archived: boolean;
  pinned: boolean;
  isOnline: boolean;
}

export interface GetOrCreateDirectRequest {
  userId: string;
  targetUserId: string;
}

export interface CreateGroupRequest {
  name: string;
  creatorId: string;
  participantIds: string[];
  avatar?: string | undefined;
}

export interface GetConversationsRequest {
  userId: string;
  page: number;
  limit: number;
  archived?: boolean | undefined;
}

export interface GetConversationsResponse {
  success: boolean;
  conversations: ConversationItem[];
  total: number;
  page: number;
}

export interface GetConversationRequest {
  conversationId: string;
  userId: string;
}

export interface AddGroupMemberRequest {
  conversationId: string;
  adminId: string;
  userId: string;
  role?: string | undefined;
}

export interface RemoveGroupMemberRequest {
  conversationId: string;
  adminId: string;
  userId: string;
}

export interface LeaveGroupRequest {
  conversationId: string;
  userId: string;
}

export interface UpdateMemberRoleRequest {
  conversationId: string;
  adminId: string;
  userId: string;
  role: string;
}

export interface MuteConversationRequest {
  conversationId: string;
  userId: string;
  muted: boolean;
  mutedUntil?: string | undefined;
}

export interface ArchiveConversationRequest {
  conversationId: string;
  userId: string;
  archived: boolean;
}

export interface PinConversationRequest {
  conversationId: string;
  userId: string;
  pinned: boolean;
}

export interface SendEncryptedMessageRequest {
  conversationId: string;
  senderId: string;
  senderDeviceId: string;
  type: string;
  envelopes: MessageEnvelope[];
  attachments: EncryptedAttachment[];
  replyToMessageId?: string | undefined;
  forwardedFromMessageId?: string | undefined;
  clientMessageId?: string | undefined;
}

export interface EnvelopeRecord {
  id: string;
  messageId: string;
  recipientUserId: string;
  recipientDeviceId: string;
  payload: CipherPayload | undefined;
  delivered: boolean;
  deliveredAt?: number | undefined;
  createdAt: string;
}

export interface EncryptedMessage {
  id: string;
  conversationId: string;
  senderId: string;
  senderDeviceId: string;
  type: string;
  replyToMessageId?: string | undefined;
  forwardedFromMessageId?: string | undefined;
  clientMessageId?: string | undefined;
  isDeleted: boolean;
  isEdited: boolean;
  editedAt?: number | undefined;
  attachments: EncryptedAttachment[];
  envelopes: EnvelopeRecord[];
  createdAt: string;
  updatedAt: string;
}

export interface EncryptedMessageResponse {
  success: boolean;
  message: string;
  encryptedMessage: EncryptedMessage | undefined;
}

export interface GetMessagesRequest {
  conversationId: string;
  userId: string;
  deviceId: string;
  page: number;
  limit: number;
  beforeMessageId?: string | undefined;
  afterMessageId?: string | undefined;
}

export interface GetMessagesResponse {
  success: boolean;
  messages: EncryptedMessage[];
  total: number;
  page: number;
  hasMore: boolean;
}

export interface GetPendingEnvelopesRequest {
  userId: string;
  deviceId: string;
  limit: number;
}

export interface GetPendingEnvelopesResponse {
  success: boolean;
  envelopes: EnvelopeRecord[];
}

export interface EditEncryptedMessageRequest {
  messageId: string;
  senderId: string;
  senderDeviceId: string;
  envelopes: MessageEnvelope[];
}

export interface DeleteMessageRequest {
  messageId: string;
  userId: string;
  forEveryone: boolean;
}

export interface ForwardMessageRequest {
  sourceMessageId: string;
  targetConversationId: string;
  senderId: string;
  senderDeviceId: string;
  envelopes: MessageEnvelope[];
  attachments: EncryptedAttachment[];
}

export interface MarkReceiptRequest {
  messageId: string;
  userId: string;
  deviceId: string;
  status: string;
}

export interface MarkConversationReadRequest {
  conversationId: string;
  userId: string;
  deviceId: string;
  upToMessageId?: string | undefined;
}

export interface ReactToMessageRequest {
  messageId: string;
  userId: string;
  deviceId: string;
  emoji: string;
}

export interface PinMessageRequest {
  conversationId: string;
  messageId: string;
  userId: string;
  pinned: boolean;
}

export interface UploadSenderKeyRequest {
  conversationId: string;
  senderId: string;
  senderDeviceId: string;
  distributions: MessageEnvelope[];
}

export interface SenderKeyDistribution {
  id: string;
  conversationId: string;
  senderUserId: string;
  senderDeviceId: string;
  recipientUserId: string;
  recipientDeviceId: string;
  payload: CipherPayload | undefined;
  createdAt: string;
}

export interface GetSenderKeyRequest {
  conversationId: string;
  userId: string;
  deviceId: string;
}

export interface GetSenderKeyResponse {
  success: boolean;
  distributions: SenderKeyDistribution[];
}

export interface GetUnreadCountsRequest {
  userId: string;
}

export interface UnreadCountItem {
  conversationId: string;
  count: number;
}

export interface GetUnreadCountsResponse {
  success: boolean;
  items: UnreadCountItem[];
  totalUnread: number;
}

export const E2EE_CHAT_PACKAGE_NAME = 'e2ee_chat';

export interface E2eeChatServiceClient {
  /** Conversations */

  getOrCreateDirectConversation(
    request: GetOrCreateDirectRequest,
  ): Observable<ConversationResponse>;

  createGroup(request: CreateGroupRequest): Observable<ConversationResponse>;

  getConversations(
    request: GetConversationsRequest,
  ): Observable<GetConversationsResponse>;

  getConversation(
    request: GetConversationRequest,
  ): Observable<ConversationResponse>;

  /** Members */

  addGroupMember(request: AddGroupMemberRequest): Observable<OperationResponse>;

  removeGroupMember(
    request: RemoveGroupMemberRequest,
  ): Observable<OperationResponse>;

  leaveGroup(request: LeaveGroupRequest): Observable<OperationResponse>;

  updateMemberRole(
    request: UpdateMemberRoleRequest,
  ): Observable<OperationResponse>;

  muteConversation(
    request: MuteConversationRequest,
  ): Observable<OperationResponse>;

  archiveConversation(
    request: ArchiveConversationRequest,
  ): Observable<OperationResponse>;

  pinConversation(
    request: PinConversationRequest,
  ): Observable<OperationResponse>;

  /** Messages (ciphertext only) */

  sendEncryptedMessage(
    request: SendEncryptedMessageRequest,
  ): Observable<EncryptedMessageResponse>;

  getMessages(request: GetMessagesRequest): Observable<GetMessagesResponse>;

  getPendingEnvelopes(
    request: GetPendingEnvelopesRequest,
  ): Observable<GetPendingEnvelopesResponse>;

  editEncryptedMessage(
    request: EditEncryptedMessageRequest,
  ): Observable<EncryptedMessageResponse>;

  deleteMessage(request: DeleteMessageRequest): Observable<OperationResponse>;

  forwardMessage(
    request: ForwardMessageRequest,
  ): Observable<EncryptedMessageResponse>;

  /** Receipts */

  markReceipt(request: MarkReceiptRequest): Observable<OperationResponse>;

  markConversationRead(
    request: MarkConversationReadRequest,
  ): Observable<OperationResponse>;

  /** Reactions / Pins */

  reactToMessage(request: ReactToMessageRequest): Observable<OperationResponse>;

  pinMessage(request: PinMessageRequest): Observable<OperationResponse>;

  /** Group sender keys */

  uploadSenderKeyDistributions(
    request: UploadSenderKeyRequest,
  ): Observable<OperationResponse>;

  getSenderKeyDistributions(
    request: GetSenderKeyRequest,
  ): Observable<GetSenderKeyResponse>;

  /** Presence helpers (conversation-scoped) */

  getUnreadCounts(
    request: GetUnreadCountsRequest,
  ): Observable<GetUnreadCountsResponse>;

  getGroupMembersForNotif(
    request: GetGroupMembersForNotifRequest,
  ): Observable<GetGroupMembersForNotifResponse>;
}

export interface E2eeChatServiceController {
  /** Conversations */

  getOrCreateDirectConversation(
    request: GetOrCreateDirectRequest,
  ):
    | Promise<ConversationResponse>
    | Observable<ConversationResponse>
    | ConversationResponse;

  createGroup(
    request: CreateGroupRequest,
  ):
    | Promise<ConversationResponse>
    | Observable<ConversationResponse>
    | ConversationResponse;

  getConversations(
    request: GetConversationsRequest,
  ):
    | Promise<GetConversationsResponse>
    | Observable<GetConversationsResponse>
    | GetConversationsResponse;

  getConversation(
    request: GetConversationRequest,
  ):
    | Promise<ConversationResponse>
    | Observable<ConversationResponse>
    | ConversationResponse;

  /** Members */

  addGroupMember(
    request: AddGroupMemberRequest,
  ):
    | Promise<OperationResponse>
    | Observable<OperationResponse>
    | OperationResponse;

  removeGroupMember(
    request: RemoveGroupMemberRequest,
  ):
    | Promise<OperationResponse>
    | Observable<OperationResponse>
    | OperationResponse;

  leaveGroup(
    request: LeaveGroupRequest,
  ):
    | Promise<OperationResponse>
    | Observable<OperationResponse>
    | OperationResponse;

  updateMemberRole(
    request: UpdateMemberRoleRequest,
  ):
    | Promise<OperationResponse>
    | Observable<OperationResponse>
    | OperationResponse;

  muteConversation(
    request: MuteConversationRequest,
  ):
    | Promise<OperationResponse>
    | Observable<OperationResponse>
    | OperationResponse;

  archiveConversation(
    request: ArchiveConversationRequest,
  ):
    | Promise<OperationResponse>
    | Observable<OperationResponse>
    | OperationResponse;

  pinConversation(
    request: PinConversationRequest,
  ):
    | Promise<OperationResponse>
    | Observable<OperationResponse>
    | OperationResponse;

  /** Messages (ciphertext only) */

  sendEncryptedMessage(
    request: SendEncryptedMessageRequest,
  ):
    | Promise<EncryptedMessageResponse>
    | Observable<EncryptedMessageResponse>
    | EncryptedMessageResponse;

  getMessages(
    request: GetMessagesRequest,
  ):
    | Promise<GetMessagesResponse>
    | Observable<GetMessagesResponse>
    | GetMessagesResponse;

  getPendingEnvelopes(
    request: GetPendingEnvelopesRequest,
  ):
    | Promise<GetPendingEnvelopesResponse>
    | Observable<GetPendingEnvelopesResponse>
    | GetPendingEnvelopesResponse;

  editEncryptedMessage(
    request: EditEncryptedMessageRequest,
  ):
    | Promise<EncryptedMessageResponse>
    | Observable<EncryptedMessageResponse>
    | EncryptedMessageResponse;

  deleteMessage(
    request: DeleteMessageRequest,
  ):
    | Promise<OperationResponse>
    | Observable<OperationResponse>
    | OperationResponse;

  forwardMessage(
    request: ForwardMessageRequest,
  ):
    | Promise<EncryptedMessageResponse>
    | Observable<EncryptedMessageResponse>
    | EncryptedMessageResponse;

  /** Receipts */

  markReceipt(
    request: MarkReceiptRequest,
  ):
    | Promise<OperationResponse>
    | Observable<OperationResponse>
    | OperationResponse;

  markConversationRead(
    request: MarkConversationReadRequest,
  ):
    | Promise<OperationResponse>
    | Observable<OperationResponse>
    | OperationResponse;

  /** Reactions / Pins */

  reactToMessage(
    request: ReactToMessageRequest,
  ):
    | Promise<OperationResponse>
    | Observable<OperationResponse>
    | OperationResponse;

  pinMessage(
    request: PinMessageRequest,
  ):
    | Promise<OperationResponse>
    | Observable<OperationResponse>
    | OperationResponse;

  /** Group sender keys */

  uploadSenderKeyDistributions(
    request: UploadSenderKeyRequest,
  ):
    | Promise<OperationResponse>
    | Observable<OperationResponse>
    | OperationResponse;

  getSenderKeyDistributions(
    request: GetSenderKeyRequest,
  ):
    | Promise<GetSenderKeyResponse>
    | Observable<GetSenderKeyResponse>
    | GetSenderKeyResponse;

  /** Presence helpers (conversation-scoped) */

  getUnreadCounts(
    request: GetUnreadCountsRequest,
  ):
    | Promise<GetUnreadCountsResponse>
    | Observable<GetUnreadCountsResponse>
    | GetUnreadCountsResponse;

  getGroupMembersForNotif(
    request: GetGroupMembersForNotifRequest,
  ):
    | Promise<GetGroupMembersForNotifResponse>
    | Observable<GetGroupMembersForNotifResponse>
    | GetGroupMembersForNotifResponse;
}

export function E2eeChatServiceControllerMethods() {
  return function (constructor: Function) {
    const grpcMethods: string[] = [
      'getOrCreateDirectConversation',
      'createGroup',
      'getConversations',
      'getConversation',
      'addGroupMember',
      'removeGroupMember',
      'leaveGroup',
      'updateMemberRole',
      'muteConversation',
      'archiveConversation',
      'pinConversation',
      'sendEncryptedMessage',
      'getMessages',
      'getPendingEnvelopes',
      'editEncryptedMessage',
      'deleteMessage',
      'forwardMessage',
      'markReceipt',
      'markConversationRead',
      'reactToMessage',
      'pinMessage',
      'uploadSenderKeyDistributions',
      'getSenderKeyDistributions',
      'getUnreadCounts',
      'getGroupMembersForNotif',
    ];
    for (const method of grpcMethods) {
      const descriptor: any = Reflect.getOwnPropertyDescriptor(
        constructor.prototype,
        method,
      );
      GrpcMethod('E2eeChatService', method)(
        constructor.prototype[method],
        method,
        descriptor,
      );
    }
    const grpcStreamMethods: string[] = [];
    for (const method of grpcStreamMethods) {
      const descriptor: any = Reflect.getOwnPropertyDescriptor(
        constructor.prototype,
        method,
      );
      GrpcStreamMethod('E2eeChatService', method)(
        constructor.prototype[method],
        method,
        descriptor,
      );
    }
  };
}

export const E2EE_CHAT_SERVICE_NAME = 'E2eeChatService';
