// Code generated by protoc-gen-ts_proto. DO NOT EDIT.
// versions:
//   protoc-gen-ts_proto  v2.11.10
//   protoc               v3.19.1
// source: feed.proto

/* eslint-disable */
import { GrpcMethod, GrpcStreamMethod } from '@nestjs/microservices';
import { Observable } from 'rxjs';

export const protobufPackage = 'feed';

/** proto/feed.proto */

export interface GetFeedRequest {
  userId: string;
  page: number;
  limit: number;
  cursor: string;
}

export interface ExploreRequest {
  userId: string;
  page: number;
  limit: number;
}

export interface TrendingRequest {
  limit: number;
}

export interface InvalidateRequest {
  userId: string;
}

export interface InvalidateResponse {
  success: boolean;
}

export interface Media {
  id: string;
  url: string;
  mimeType: string;
  type: string;
}

export interface User {
  id: string;
  username: string;
  fullName: string;
  avatar: string;
  verified: boolean;
}

export interface FeedPost {
  id: string;
  content: string;
  feeling: string;
  location: string;
  likesCount: number;
  commentsCount: number;
  sharesCount: number;
  viewsCount: number;
  isLiked: boolean;
  isBookmarked: boolean;
  createdAt: string;
  author: User | undefined;
  media: Media[];
}

export interface FeedResponse {
  success: boolean;
  posts: FeedPost[];
  total: number;
  nextCursor: string;
  hasMore: boolean;
}

export const FEED_PACKAGE_NAME = 'feed';

export interface FeedServiceClient {
  getFeed(request: GetFeedRequest): Observable<FeedResponse>;

  getExploreFeed(request: ExploreRequest): Observable<FeedResponse>;

  getTrendingPosts(request: TrendingRequest): Observable<FeedResponse>;

  invalidateFeed(request: InvalidateRequest): Observable<InvalidateResponse>;
}

export interface FeedServiceController {
  getFeed(
    request: GetFeedRequest,
  ): Promise<FeedResponse> | Observable<FeedResponse> | FeedResponse;

  getExploreFeed(
    request: ExploreRequest,
  ): Promise<FeedResponse> | Observable<FeedResponse> | FeedResponse;

  getTrendingPosts(
    request: TrendingRequest,
  ): Promise<FeedResponse> | Observable<FeedResponse> | FeedResponse;

  invalidateFeed(
    request: InvalidateRequest,
  ):
    | Promise<InvalidateResponse>
    | Observable<InvalidateResponse>
    | InvalidateResponse;
}

export function FeedServiceControllerMethods() {
  return function (constructor: Function) {
    const grpcMethods: string[] = [
      'getFeed',
      'getExploreFeed',
      'getTrendingPosts',
      'invalidateFeed',
    ];
    for (const method of grpcMethods) {
      const descriptor: any = Reflect.getOwnPropertyDescriptor(
        constructor.prototype,
        method,
      );
      GrpcMethod('FeedService', method)(
        constructor.prototype[method],
        method,
        descriptor,
      );
    }
    const grpcStreamMethods: string[] = [];
    for (const method of grpcStreamMethods) {
      const descriptor: any = Reflect.getOwnPropertyDescriptor(
        constructor.prototype,
        method,
      );
      GrpcStreamMethod('FeedService', method)(
        constructor.prototype[method],
        method,
        descriptor,
      );
    }
  };
}

export const FEED_SERVICE_NAME = 'FeedService';
