// Code generated by protoc-gen-ts_proto. DO NOT EDIT.
// versions:
//   protoc-gen-ts_proto  v2.11.10
//   protoc               v3.19.1
// source: mcp.proto

/* eslint-disable */
import { GrpcMethod, GrpcStreamMethod } from '@nestjs/microservices';
import { Observable } from 'rxjs';

export const protobufPackage = 'mcp';

export interface AskRequest {
  userId: string;
  prompt: string;
}

export interface ToolTraceItem {
  toolName: string;
  rawArgs: string;
  result: string;
}

export interface AskResponse {
  success: boolean;
  message: string;
  answer: string;
  trace: ToolTraceItem[];
}

export const MCP_PACKAGE_NAME = 'mcp';

export interface AgentServiceClient {
  ask(request: AskRequest): Observable<AskResponse>;
}

export interface AgentServiceController {
  ask(
    request: AskRequest,
  ): Promise<AskResponse> | Observable<AskResponse> | AskResponse;
}

export function AgentServiceControllerMethods() {
  return function (constructor: Function) {
    const grpcMethods: string[] = ['ask'];
    for (const method of grpcMethods) {
      const descriptor: any = Reflect.getOwnPropertyDescriptor(
        constructor.prototype,
        method,
      );
      GrpcMethod('AgentService', method)(
        constructor.prototype[method],
        method,
        descriptor,
      );
    }
    const grpcStreamMethods: string[] = [];
    for (const method of grpcStreamMethods) {
      const descriptor: any = Reflect.getOwnPropertyDescriptor(
        constructor.prototype,
        method,
      );
      GrpcStreamMethod('AgentService', method)(
        constructor.prototype[method],
        method,
        descriptor,
      );
    }
  };
}

export const AGENT_SERVICE_NAME = 'AgentService';
