// Code generated by protoc-gen-ts_proto. DO NOT EDIT.
// versions:
//   protoc-gen-ts_proto  v2.11.10
//   protoc               v3.19.1
// source: media.proto

/* eslint-disable */
import { GrpcMethod, GrpcStreamMethod } from '@nestjs/microservices';
import { Observable } from 'rxjs';

export const protobufPackage = 'media';

export enum MediaType {
  MEDIA_TYPE_UNKNOWN = 0,
  IMAGE = 1,
  VIDEO = 2,
  AUDIO = 3,
  FILE = 4,
  AVATAR = 5,
  COVER = 6,
  UNRECOGNIZED = -1,
}

export enum MediaStatus {
  PENDING = 0,
  PROCESSING = 1,
  DONE = 2,
  FAILED = 3,
  UNRECOGNIZED = -1,
}

export interface UploadImageRequest {
  userId: string;
  buffer: Uint8Array;
  originalName: string;
  mimeType: string;
}

export interface GetMediaByIdsRequest {
  mediaIds: string[];
}

export interface GetMediaListResponse {
  success: boolean;
  message: string;
  media: Media[];
}

export interface Media {
  id: string;
  userId: string;
  type: MediaType;
  originalName: string;
  fileName: string;
  path: string;
  originalUrl: string;
  thumbnailUrl: string;
  mediaIds: string;
  mimeType: string;
  size: number;
  status: MediaStatus;
  width: number;
  height: number;
  duration: number;
  createdAt: string;
  updatedAt: string;
}

export interface CreateMediaRequest {
  userId: string;
  type: MediaType;
  originalName: string;
  fileName: string;
  path: string;
  originalUrl: string;
  thumbnailUrl: string;
  mediaIds: string;
  mimeType: string;
  size: number;
  status: MediaStatus;
  width: number;
  height: number;
  duration: number;
}

export interface GetMediaRequest {
  mediaId: string;
}

export interface GetMediaByPathRequest {
  path: string;
}

export interface ListUserMediaRequest {
  userId: string;
  type: string;
  page: number;
  limit: number;
}

export interface UpdateMediaStatusRequest {
  mediaId: string;
  status: MediaStatus;
  originalUrl: string;
  thumbnailUrl: string;
  mediaIds: string;
}

export interface DeleteMediaRequest {
  mediaId: string;
  userId: string;
}

export interface ExistsRequest {
  mediaId: string;
}

export interface ExistsResponse {
  success: boolean;
  message: string;
  exists: boolean;
}

export interface MediaResponse {
  success: boolean;
  message: string;
  media: Media | undefined;
}

export interface ListUserMediaResponse {
  success: boolean;
  message: string;
  media: Media[];
  total: number;
  page: number;
  limit: number;
}

export interface DeleteMediaResponse {
  success: boolean;
  message: string;
}

export const MEDIA_PACKAGE_NAME = 'media';

export interface MediaServiceClient {
  uploadImage(request: UploadImageRequest): Observable<MediaResponse>;

  createMedia(request: CreateMediaRequest): Observable<MediaResponse>;

  getMedia(request: GetMediaRequest): Observable<MediaResponse>;

  listUserMedia(
    request: ListUserMediaRequest,
  ): Observable<ListUserMediaResponse>;

  deleteMedia(request: DeleteMediaRequest): Observable<DeleteMediaResponse>;

  updateMediaStatus(
    request: UpdateMediaStatusRequest,
  ): Observable<MediaResponse>;

  getMediaByPath(request: GetMediaByPathRequest): Observable<MediaResponse>;

  exists(request: ExistsRequest): Observable<ExistsResponse>;

  getMediaByIds(
    request: GetMediaByIdsRequest,
  ): Observable<GetMediaListResponse>;
}

export interface MediaServiceController {
  uploadImage(
    request: UploadImageRequest,
  ): Promise<MediaResponse> | Observable<MediaResponse> | MediaResponse;

  createMedia(
    request: CreateMediaRequest,
  ): Promise<MediaResponse> | Observable<MediaResponse> | MediaResponse;

  getMedia(
    request: GetMediaRequest,
  ): Promise<MediaResponse> | Observable<MediaResponse> | MediaResponse;

  listUserMedia(
    request: ListUserMediaRequest,
  ):
    | Promise<ListUserMediaResponse>
    | Observable<ListUserMediaResponse>
    | ListUserMediaResponse;

  deleteMedia(
    request: DeleteMediaRequest,
  ):
    | Promise<DeleteMediaResponse>
    | Observable<DeleteMediaResponse>
    | DeleteMediaResponse;

  updateMediaStatus(
    request: UpdateMediaStatusRequest,
  ): Promise<MediaResponse> | Observable<MediaResponse> | MediaResponse;

  getMediaByPath(
    request: GetMediaByPathRequest,
  ): Promise<MediaResponse> | Observable<MediaResponse> | MediaResponse;

  exists(
    request: ExistsRequest,
  ): Promise<ExistsResponse> | Observable<ExistsResponse> | ExistsResponse;

  getMediaByIds(
    request: GetMediaByIdsRequest,
  ):
    | Promise<GetMediaListResponse>
    | Observable<GetMediaListResponse>
    | GetMediaListResponse;
}

export function MediaServiceControllerMethods() {
  return function (constructor: Function) {
    const grpcMethods: string[] = [
      'uploadImage',
      'createMedia',
      'getMedia',
      'listUserMedia',
      'deleteMedia',
      'updateMediaStatus',
      'getMediaByPath',
      'exists',
      'getMediaByIds',
    ];
    for (const method of grpcMethods) {
      const descriptor: any = Reflect.getOwnPropertyDescriptor(
        constructor.prototype,
        method,
      );
      GrpcMethod('MediaService', method)(
        constructor.prototype[method],
        method,
        descriptor,
      );
    }
    const grpcStreamMethods: string[] = [];
    for (const method of grpcStreamMethods) {
      const descriptor: any = Reflect.getOwnPropertyDescriptor(
        constructor.prototype,
        method,
      );
      GrpcStreamMethod('MediaService', method)(
        constructor.prototype[method],
        method,
        descriptor,
      );
    }
  };
}

export const MEDIA_SERVICE_NAME = 'MediaService';
