// Code generated by protoc-gen-ts_proto. DO NOT EDIT.
// versions:
//   protoc-gen-ts_proto  v2.11.10
//   protoc               v3.19.1
// source: notification.proto

/* eslint-disable */
import { GrpcMethod, GrpcStreamMethod } from '@nestjs/microservices';
import { Observable } from 'rxjs';

export const protobufPackage = 'notification';

export interface User {
  id: string;
  username: string;
  fullName: string;
  avatar: string;
  verified: boolean;
}

export interface Notification {
  id: string;
  toUserId: string;
  sender: User | undefined;
  type: string;
  title: string;
  body: string;
  createdAt: string;
  isRead: boolean;
  data: { [key: string]: string };
}

export interface Notification_DataEntry {
  key: string;
  value: string;
}

export interface GetNotificationsRequest {
  userId: string;
  page: number;
  limit: number;
}

export interface GetNotificationsResponse {
  notifications: Notification[];
  total: number;
  unreadCount: number;
  page: number;
}

export interface MarkAsReadRequest {
  userId: string;
  notificationId: string;
}

export interface MarkAllAsReadRequest {
  userId: string;
}

export interface DeleteNotificationRequest {
  userId: string;
  notificationId: string;
}

export interface GetPreferencesRequest {
  userId: string;
}

export interface UpdatePreferencesRequest {
  userId: string;
  likes: boolean;
  comments: boolean;
  follows: boolean;
  unfollows: boolean;
  mentions: boolean;
  messages: boolean;
}

export interface NotificationPreference {
  userId: string;
  likes: boolean;
  comments: boolean;
  follows: boolean;
  unfollows: boolean;
  mentions: boolean;
  messages: boolean;
}

export interface ActionResponse {
  success: boolean;
  message: string;
}

export const NOTIFICATION_PACKAGE_NAME = 'notification';

export interface NotificationGrpcServiceClient {
  getNotifications(
    request: GetNotificationsRequest,
  ): Observable<GetNotificationsResponse>;

  markAsRead(request: MarkAsReadRequest): Observable<ActionResponse>;

  markAllAsRead(request: MarkAllAsReadRequest): Observable<ActionResponse>;

  deleteNotification(
    request: DeleteNotificationRequest,
  ): Observable<ActionResponse>;

  getPreferences(
    request: GetPreferencesRequest,
  ): Observable<NotificationPreference>;

  updatePreferences(
    request: UpdatePreferencesRequest,
  ): Observable<NotificationPreference>;
}

export interface NotificationGrpcServiceController {
  getNotifications(
    request: GetNotificationsRequest,
  ):
    | Promise<GetNotificationsResponse>
    | Observable<GetNotificationsResponse>
    | GetNotificationsResponse;

  markAsRead(
    request: MarkAsReadRequest,
  ): Promise<ActionResponse> | Observable<ActionResponse> | ActionResponse;

  markAllAsRead(
    request: MarkAllAsReadRequest,
  ): Promise<ActionResponse> | Observable<ActionResponse> | ActionResponse;

  deleteNotification(
    request: DeleteNotificationRequest,
  ): Promise<ActionResponse> | Observable<ActionResponse> | ActionResponse;

  getPreferences(
    request: GetPreferencesRequest,
  ):
    | Promise<NotificationPreference>
    | Observable<NotificationPreference>
    | NotificationPreference;

  updatePreferences(
    request: UpdatePreferencesRequest,
  ):
    | Promise<NotificationPreference>
    | Observable<NotificationPreference>
    | NotificationPreference;
}

export function NotificationGrpcServiceControllerMethods() {
  return function (constructor: Function) {
    const grpcMethods: string[] = [
      'getNotifications',
      'markAsRead',
      'markAllAsRead',
      'deleteNotification',
      'getPreferences',
      'updatePreferences',
    ];
    for (const method of grpcMethods) {
      const descriptor: any = Reflect.getOwnPropertyDescriptor(
        constructor.prototype,
        method,
      );
      GrpcMethod('NotificationGrpcService', method)(
        constructor.prototype[method],
        method,
        descriptor,
      );
    }
    const grpcStreamMethods: string[] = [];
    for (const method of grpcStreamMethods) {
      const descriptor: any = Reflect.getOwnPropertyDescriptor(
        constructor.prototype,
        method,
      );
      GrpcStreamMethod('NotificationGrpcService', method)(
        constructor.prototype[method],
        method,
        descriptor,
      );
    }
  };
}

export const NOTIFICATION_GRPC_SERVICE_NAME = 'NotificationGrpcService';
