// Code generated by protoc-gen-ts_proto. DO NOT EDIT.
// versions:
//   protoc-gen-ts_proto  v2.11.10
//   protoc               v3.19.1
// source: post.proto

/* eslint-disable */
import { GrpcMethod, GrpcStreamMethod } from '@nestjs/microservices';
import { Observable } from 'rxjs';

export const protobufPackage = 'post';

/** ── Enums ───────────────────────────────────────── */
export enum PostPrivacy {
  PUBLIC = 0,
  FRIENDS = 1,
  PRIVATE = 2,
  UNRECOGNIZED = -1,
}

export enum ReactionType {
  LIKE = 0,
  LOVE = 1,
  HAHA = 2,
  WOW = 3,
  SAD = 4,
  ANGRY = 5,
  UNRECOGNIZED = -1,
}

export interface GetRecentPostsByAuthorsResponse {
  success: boolean;
  posts: Post[];
  total: number;
  page: number;
}

export interface GetRecentPostsByAuthorsRequest {
  authorIds: string[];
  requesterId: string;
  limitPerAuthor: number;
}

/** ── Post Messages ───────────────────────────────── */
export interface CreatePostRequest {
  userId: string;
  content?: string | undefined;
  mediaIds: string[];
  feeling?: string | undefined;
  location?: string | undefined;
  privacy: PostPrivacy;
  taggedUsers?: string | undefined;
}

export interface GetPostRequest {
  postId: string;
  requesterId: string;
}

export interface UpdatePostRequest {
  postId: string;
  userId: string;
  content: string;
  privacy: PostPrivacy;
}

export interface DeletePostRequest {
  postId: string;
  userId: string;
}

export interface GetUserPostsRequest {
  userId: string;
  requesterId: string;
  page: number;
  limit: number;
}

export interface DeleteResponse {
  success: boolean;
  message: string;
}

/** ── Reaction Messages ───────────────────────────── */
export interface ReactionRequest {
  postId: string;
  userId: string;
}

export interface ReactRequest {
  postId: string;
  userId: string;
  reactionType: ReactionType;
}

export interface ReactionResponse {
  success: boolean;
  message: string;
  likesCount: number;
  isLiked: boolean;
  reactionType: string;
}

/** ── Comment Messages ────────────────────────────── */
export interface AddCommentRequest {
  postId: string;
  userId: string;
  text: string;
  parentId: string;
}

export interface GetCommentsRequest {
  postId: string;
  parentId: string;
  page: number;
  limit: number;
}

export interface DeleteCommentRequest {
  commentId: string;
  userId: string;
}

export interface Comment {
  id: string;
  postId: string;
  userId: string;
  text: string;
  parentId: string;
  likesCount: number;
  repliesCount: number;
  isLiked: boolean;
  createdAt: string;
  author: PostAuthor | undefined;
}

export interface CommentResponse {
  success: boolean;
  message: string;
  comment: Comment | undefined;
}

export interface CommentsListResponse {
  success: boolean;
  comments: Comment[];
  total: number;
  page: number;
}

/** ── Share & Bookmark ────────────────────────────── */
export interface ShareRequest {
  postId: string;
  userId: string;
  comment: string;
}

export interface ShareResponse {
  success: boolean;
  message: string;
  sharesCount: number;
}

/** ── View Count ──────────────────────────────────── */
export interface ViewCountRequest {
  postId: string;
  userId: string;
}

export interface ViewCountResponse {
  viewsCount: number;
}

/** ── Internal ────────────────────────────────────── */
export interface GetPostsByIdsRequest {
  postIds: string[];
  requesterId: string;
}

/** ── Post Object ─────────────────────────────────── */
export interface Post {
  id: string;
  userId: string;
  content: string;
  feeling: string;
  location: string;
  privacy: string;
  likesCount: number;
  commentsCount: number;
  sharesCount: number;
  viewsCount: number;
  isLiked: boolean;
  isBookmarked: boolean;
  reactionType: string;
  createdAt: string;
  updatedAt: string;
  media: PostMedia[];
  author: PostAuthor | undefined;
  mediaIds: string[];
}

export interface PostResponse {
  success: boolean;
  message: string;
  post: Post | undefined;
}

export interface PostsListResponse {
  success: boolean;
  posts: Post[];
  total: number;
  page: number;
}

export interface PostMedia {
  id: string;
  url: string;
  mimeType: string;
  type: string;
}

export interface PostAuthor {
  id: string;
  username: string;
  fullName: string;
  avatar: string;
  verified: boolean;
}

export const POST_PACKAGE_NAME = 'post';

export interface PostServiceClient {
  /** Post CRUD */

  createPost(request: CreatePostRequest): Observable<PostResponse>;

  getPost(request: GetPostRequest): Observable<PostResponse>;

  updatePost(request: UpdatePostRequest): Observable<PostResponse>;

  deletePost(request: DeletePostRequest): Observable<DeleteResponse>;

  getUserPosts(request: GetUserPostsRequest): Observable<PostsListResponse>;

  /** Reactions */

  likePost(request: ReactionRequest): Observable<ReactionResponse>;

  unlikePost(request: ReactionRequest): Observable<ReactionResponse>;

  reactToPost(request: ReactRequest): Observable<ReactionResponse>;

  /** Comments */

  addComment(request: AddCommentRequest): Observable<CommentResponse>;

  getComments(request: GetCommentsRequest): Observable<CommentsListResponse>;

  deleteComment(request: DeleteCommentRequest): Observable<DeleteResponse>;

  likeComment(request: ReactionRequest): Observable<ReactionResponse>;

  /** Share & Bookmark */

  sharePost(request: ShareRequest): Observable<ShareResponse>;

  bookmarkPost(request: ReactionRequest): Observable<ReactionResponse>;

  /** Internal */

  getPostsByIds(request: GetPostsByIdsRequest): Observable<PostsListResponse>;

  incrViewCount(request: ViewCountRequest): Observable<ViewCountResponse>;

  getRecentPostsByAuthors(
    request: GetRecentPostsByAuthorsRequest,
  ): Observable<GetRecentPostsByAuthorsResponse>;
}

export interface PostServiceController {
  /** Post CRUD */

  createPost(
    request: CreatePostRequest,
  ): Promise<PostResponse> | Observable<PostResponse> | PostResponse;

  getPost(
    request: GetPostRequest,
  ): Promise<PostResponse> | Observable<PostResponse> | PostResponse;

  updatePost(
    request: UpdatePostRequest,
  ): Promise<PostResponse> | Observable<PostResponse> | PostResponse;

  deletePost(
    request: DeletePostRequest,
  ): Promise<DeleteResponse> | Observable<DeleteResponse> | DeleteResponse;

  getUserPosts(
    request: GetUserPostsRequest,
  ):
    | Promise<PostsListResponse>
    | Observable<PostsListResponse>
    | PostsListResponse;

  /** Reactions */

  likePost(
    request: ReactionRequest,
  ):
    | Promise<ReactionResponse>
    | Observable<ReactionResponse>
    | ReactionResponse;

  unlikePost(
    request: ReactionRequest,
  ):
    | Promise<ReactionResponse>
    | Observable<ReactionResponse>
    | ReactionResponse;

  reactToPost(
    request: ReactRequest,
  ):
    | Promise<ReactionResponse>
    | Observable<ReactionResponse>
    | ReactionResponse;

  /** Comments */

  addComment(
    request: AddCommentRequest,
  ): Promise<CommentResponse> | Observable<CommentResponse> | CommentResponse;

  getComments(
    request: GetCommentsRequest,
  ):
    | Promise<CommentsListResponse>
    | Observable<CommentsListResponse>
    | CommentsListResponse;

  deleteComment(
    request: DeleteCommentRequest,
  ): Promise<DeleteResponse> | Observable<DeleteResponse> | DeleteResponse;

  likeComment(
    request: ReactionRequest,
  ):
    | Promise<ReactionResponse>
    | Observable<ReactionResponse>
    | ReactionResponse;

  /** Share & Bookmark */

  sharePost(
    request: ShareRequest,
  ): Promise<ShareResponse> | Observable<ShareResponse> | ShareResponse;

  bookmarkPost(
    request: ReactionRequest,
  ):
    | Promise<ReactionResponse>
    | Observable<ReactionResponse>
    | ReactionResponse;

  /** Internal */

  getPostsByIds(
    request: GetPostsByIdsRequest,
  ):
    | Promise<PostsListResponse>
    | Observable<PostsListResponse>
    | PostsListResponse;

  incrViewCount(
    request: ViewCountRequest,
  ):
    | Promise<ViewCountResponse>
    | Observable<ViewCountResponse>
    | ViewCountResponse;

  getRecentPostsByAuthors(
    request: GetRecentPostsByAuthorsRequest,
  ):
    | Promise<GetRecentPostsByAuthorsResponse>
    | Observable<GetRecentPostsByAuthorsResponse>
    | GetRecentPostsByAuthorsResponse;
}

export function PostServiceControllerMethods() {
  return function (constructor: Function) {
    const grpcMethods: string[] = [
      'createPost',
      'getPost',
      'updatePost',
      'deletePost',
      'getUserPosts',
      'likePost',
      'unlikePost',
      'reactToPost',
      'addComment',
      'getComments',
      'deleteComment',
      'likeComment',
      'sharePost',
      'bookmarkPost',
      'getPostsByIds',
      'incrViewCount',
      'getRecentPostsByAuthors',
    ];
    for (const method of grpcMethods) {
      const descriptor: any = Reflect.getOwnPropertyDescriptor(
        constructor.prototype,
        method,
      );
      GrpcMethod('PostService', method)(
        constructor.prototype[method],
        method,
        descriptor,
      );
    }
    const grpcStreamMethods: string[] = [];
    for (const method of grpcStreamMethods) {
      const descriptor: any = Reflect.getOwnPropertyDescriptor(
        constructor.prototype,
        method,
      );
      GrpcStreamMethod('PostService', method)(
        constructor.prototype[method],
        method,
        descriptor,
      );
    }
  };
}

export const POST_SERVICE_NAME = 'PostService';
