// Code generated by protoc-gen-ts_proto. DO NOT EDIT.
// versions:
//   protoc-gen-ts_proto  v2.11.10
//   protoc               v3.19.1
// source: user.proto

/* eslint-disable */
import { GrpcMethod, GrpcStreamMethod } from '@nestjs/microservices';
import { Observable } from 'rxjs';

export const protobufPackage = 'user';

/** ── Profile Messages ────────────────────────────── */
export interface GetProfileRequest {
  userId: string;
  requesterId: string;
}

export interface UpdateProfileRequest {
  userId: string;
  name?: string | undefined;
  bio?: string | undefined;
  avatarMediaId?: string | undefined;
  coverMediaId?: string | undefined;
  location?: string | undefined;
  website?: string | undefined;
  birthDate?: string | undefined;
}

export interface DeleteAccountRequest {
  userId: string;
}

export interface DeleteResponse {
  success: boolean;
  message: string;
}

/** ── Follow Messages ─────────────────────────────── */
export interface FollowRequest {
  followerId: string;
  targetId: string;
}

export interface FollowResponse {
  success: boolean;
  message: string;
  followersCount: number;
  isFollowing: boolean;
}

export interface IsFollowingResponse {
  isFollowing: boolean;
}

export interface PaginationRequest {
  userId: string;
  page: number;
  limit: number;
}

/** ── Search Messages ─────────────────────────────── */
export interface SearchRequest {
  query: string;
  requesterId: string;
  page: number;
  limit: number;
}

export interface SuggestionRequest {
  userId: string;
  limit: number;
}

/** ── Presence Messages ───────────────────────────── */
export interface PresenceRequest {
  userId: string;
}

export interface PresenceResponse {
  isOnline: boolean;
  lastSeen: number;
}

export interface UserMedia {
  id: string;
  url: string;
  mimeType: string;
  type: string;
}

export interface UserProfile {
  id: string;
  name: string;
  email: string;
  bio: string;
  avatar: UserMedia | undefined;
  coverImg: UserMedia | undefined;
  location: string;
  website: string;
  birthDate: string;
  followersCount: number;
  followingCount: number;
  postsCount: number;
  isFollowing: boolean;
  isOnline: boolean;
  createdAt: string;
}

export interface ProfileResponse {
  success: boolean;
  message: string;
  user: UserProfile | undefined;
}

export interface UsersListResponse {
  success: boolean;
  users: UserProfile[];
  total: number;
  page: number;
}

export interface GetUsersByIdsRequest {
  userIds: string[];
}

export interface GetFollowerIdsRequest {
  userId: string;
}

export interface FollowerIdsResponse {
  followerIds: string[];
}

export interface OperationResponse {
  success: boolean;
  message: string;
}

/** ── E2EE Devices & Keys ─────────────────────────── */
export interface RegisterDeviceRequest {
  userId: string;
  deviceId: string;
  deviceName: string;
  platform: string;
  osVersion?: string | undefined;
  appVersion?: string | undefined;
}

export interface DeviceInfo {
  id: string;
  deviceId: string;
  deviceName: string;
  platform: string;
  osVersion: string;
  appVersion: string;
  isActive: boolean;
  lastSeenAt: number;
  createdAt: string;
}

export interface DeviceResponse {
  success: boolean;
  message: string;
  device: DeviceInfo | undefined;
}

export interface ListDevicesRequest {
  userId: string;
}

export interface ListDevicesResponse {
  success: boolean;
  devices: DeviceInfo[];
}

export interface RevokeDeviceRequest {
  userId: string;
  deviceId: string;
}

export interface IdentityKeyData {
  publicKey: string;
  registrationId: number;
}

export interface SignedPreKeyData {
  keyId: number;
  publicKey: string;
  signature: string;
}

export interface OneTimePreKeyData {
  keyId: number;
  publicKey: string;
}

export interface UploadKeysRequest {
  userId: string;
  deviceId: string;
  identityKey: IdentityKeyData | undefined;
  signedPreKey: SignedPreKeyData | undefined;
  oneTimePreKeys: OneTimePreKeyData[];
}

export interface RotateSignedPreKeyRequest {
  userId: string;
  deviceId: string;
  signedPreKey: SignedPreKeyData | undefined;
}

export interface RefillOneTimePreKeysRequest {
  userId: string;
  deviceId: string;
  oneTimePreKeys: OneTimePreKeyData[];
}

export interface GetKeyBundleRequest {
  targetUserId: string;
  deviceId?: string | undefined;
  requesterId: string;
}

export interface DeviceKeyBundle {
  deviceId: string;
  platform: string;
  deviceName: string;
  identityKey: IdentityKeyData | undefined;
  signedPreKey: SignedPreKeyData | undefined;
  oneTimePreKey?: OneTimePreKeyData | undefined;
  registrationId: number;
}

export interface KeyBundleResponse {
  success: boolean;
  message: string;
  userId: string;
  devices: DeviceKeyBundle[];
}

export interface GetKeyBundlesForUsersRequest {
  userIds: string[];
  requesterId: string;
}

export interface UserKeyBundles {
  userId: string;
  devices: DeviceKeyBundle[];
}

export interface KeyBundlesResponse {
  success: boolean;
  bundles: UserKeyBundles[];
}

export interface CountOneTimePreKeysRequest {
  userId: string;
  deviceId: string;
}

export interface CountOneTimePreKeysResponse {
  success: boolean;
  count: number;
}

export const USER_PACKAGE_NAME = 'user';

export interface UserServiceClient {
  /** Profile */

  getProfile(request: GetProfileRequest): Observable<ProfileResponse>;

  updateProfile(request: UpdateProfileRequest): Observable<ProfileResponse>;

  deleteAccount(request: DeleteAccountRequest): Observable<DeleteResponse>;

  /** Follow System */

  followUser(request: FollowRequest): Observable<FollowResponse>;

  unfollowUser(request: FollowRequest): Observable<FollowResponse>;

  getFollowers(request: PaginationRequest): Observable<UsersListResponse>;

  getFollowing(request: PaginationRequest): Observable<UsersListResponse>;

  isFollowing(request: FollowRequest): Observable<IsFollowingResponse>;

  /** Search & Suggest */

  searchUsers(request: SearchRequest): Observable<UsersListResponse>;

  getSuggestions(request: SuggestionRequest): Observable<UsersListResponse>;

  /** Presence */

  setOnline(request: PresenceRequest): Observable<PresenceResponse>;

  setOffline(request: PresenceRequest): Observable<PresenceResponse>;

  getOnlineStatus(request: PresenceRequest): Observable<PresenceResponse>;

  /** Internal — other services call */

  getUsersByIds(request: GetUsersByIdsRequest): Observable<UsersListResponse>;

  getFollowerIds(
    request: GetFollowerIdsRequest,
  ): Observable<FollowerIdsResponse>;

  /** ── E2EE Device & Key Management ──────────────── */

  registerDevice(request: RegisterDeviceRequest): Observable<DeviceResponse>;

  listDevices(request: ListDevicesRequest): Observable<ListDevicesResponse>;

  revokeDevice(request: RevokeDeviceRequest): Observable<OperationResponse>;

  uploadKeys(request: UploadKeysRequest): Observable<OperationResponse>;

  rotateSignedPreKey(
    request: RotateSignedPreKeyRequest,
  ): Observable<OperationResponse>;

  refillOneTimePreKeys(
    request: RefillOneTimePreKeysRequest,
  ): Observable<OperationResponse>;

  getKeyBundle(request: GetKeyBundleRequest): Observable<KeyBundleResponse>;

  getKeyBundlesForUsers(
    request: GetKeyBundlesForUsersRequest,
  ): Observable<KeyBundlesResponse>;

  countOneTimePreKeys(
    request: CountOneTimePreKeysRequest,
  ): Observable<CountOneTimePreKeysResponse>;
}

export interface UserServiceController {
  /** Profile */

  getProfile(
    request: GetProfileRequest,
  ): Promise<ProfileResponse> | Observable<ProfileResponse> | ProfileResponse;

  updateProfile(
    request: UpdateProfileRequest,
  ): Promise<ProfileResponse> | Observable<ProfileResponse> | ProfileResponse;

  deleteAccount(
    request: DeleteAccountRequest,
  ): Promise<DeleteResponse> | Observable<DeleteResponse> | DeleteResponse;

  /** Follow System */

  followUser(
    request: FollowRequest,
  ): Promise<FollowResponse> | Observable<FollowResponse> | FollowResponse;

  unfollowUser(
    request: FollowRequest,
  ): Promise<FollowResponse> | Observable<FollowResponse> | FollowResponse;

  getFollowers(
    request: PaginationRequest,
  ):
    | Promise<UsersListResponse>
    | Observable<UsersListResponse>
    | UsersListResponse;

  getFollowing(
    request: PaginationRequest,
  ):
    | Promise<UsersListResponse>
    | Observable<UsersListResponse>
    | UsersListResponse;

  isFollowing(
    request: FollowRequest,
  ):
    | Promise<IsFollowingResponse>
    | Observable<IsFollowingResponse>
    | IsFollowingResponse;

  /** Search & Suggest */

  searchUsers(
    request: SearchRequest,
  ):
    | Promise<UsersListResponse>
    | Observable<UsersListResponse>
    | UsersListResponse;

  getSuggestions(
    request: SuggestionRequest,
  ):
    | Promise<UsersListResponse>
    | Observable<UsersListResponse>
    | UsersListResponse;

  /** Presence */

  setOnline(
    request: PresenceRequest,
  ):
    | Promise<PresenceResponse>
    | Observable<PresenceResponse>
    | PresenceResponse;

  setOffline(
    request: PresenceRequest,
  ):
    | Promise<PresenceResponse>
    | Observable<PresenceResponse>
    | PresenceResponse;

  getOnlineStatus(
    request: PresenceRequest,
  ):
    | Promise<PresenceResponse>
    | Observable<PresenceResponse>
    | PresenceResponse;

  /** Internal — other services call */

  getUsersByIds(
    request: GetUsersByIdsRequest,
  ):
    | Promise<UsersListResponse>
    | Observable<UsersListResponse>
    | UsersListResponse;

  getFollowerIds(
    request: GetFollowerIdsRequest,
  ):
    | Promise<FollowerIdsResponse>
    | Observable<FollowerIdsResponse>
    | FollowerIdsResponse;

  /** ── E2EE Device & Key Management ──────────────── */

  registerDevice(
    request: RegisterDeviceRequest,
  ): Promise<DeviceResponse> | Observable<DeviceResponse> | DeviceResponse;

  listDevices(
    request: ListDevicesRequest,
  ):
    | Promise<ListDevicesResponse>
    | Observable<ListDevicesResponse>
    | ListDevicesResponse;

  revokeDevice(
    request: RevokeDeviceRequest,
  ):
    | Promise<OperationResponse>
    | Observable<OperationResponse>
    | OperationResponse;

  uploadKeys(
    request: UploadKeysRequest,
  ):
    | Promise<OperationResponse>
    | Observable<OperationResponse>
    | OperationResponse;

  rotateSignedPreKey(
    request: RotateSignedPreKeyRequest,
  ):
    | Promise<OperationResponse>
    | Observable<OperationResponse>
    | OperationResponse;

  refillOneTimePreKeys(
    request: RefillOneTimePreKeysRequest,
  ):
    | Promise<OperationResponse>
    | Observable<OperationResponse>
    | OperationResponse;

  getKeyBundle(
    request: GetKeyBundleRequest,
  ):
    | Promise<KeyBundleResponse>
    | Observable<KeyBundleResponse>
    | KeyBundleResponse;

  getKeyBundlesForUsers(
    request: GetKeyBundlesForUsersRequest,
  ):
    | Promise<KeyBundlesResponse>
    | Observable<KeyBundlesResponse>
    | KeyBundlesResponse;

  countOneTimePreKeys(
    request: CountOneTimePreKeysRequest,
  ):
    | Promise<CountOneTimePreKeysResponse>
    | Observable<CountOneTimePreKeysResponse>
    | CountOneTimePreKeysResponse;
}

export function UserServiceControllerMethods() {
  return function (constructor: Function) {
    const grpcMethods: string[] = [
      'getProfile',
      'updateProfile',
      'deleteAccount',
      'followUser',
      'unfollowUser',
      'getFollowers',
      'getFollowing',
      'isFollowing',
      'searchUsers',
      'getSuggestions',
      'setOnline',
      'setOffline',
      'getOnlineStatus',
      'getUsersByIds',
      'getFollowerIds',
      'registerDevice',
      'listDevices',
      'revokeDevice',
      'uploadKeys',
      'rotateSignedPreKey',
      'refillOneTimePreKeys',
      'getKeyBundle',
      'getKeyBundlesForUsers',
      'countOneTimePreKeys',
    ];
    for (const method of grpcMethods) {
      const descriptor: any = Reflect.getOwnPropertyDescriptor(
        constructor.prototype,
        method,
      );
      GrpcMethod('UserService', method)(
        constructor.prototype[method],
        method,
        descriptor,
      );
    }
    const grpcStreamMethods: string[] = [];
    for (const method of grpcStreamMethods) {
      const descriptor: any = Reflect.getOwnPropertyDescriptor(
        constructor.prototype,
        method,
      );
      GrpcStreamMethod('UserService', method)(
        constructor.prototype[method],
        method,
        descriptor,
      );
    }
  };
}

export const USER_SERVICE_NAME = 'UserService';
